// <auto-generated>

#nullable enable

using System.Linq;
using System.Collections.Generic;

namespace Bdaya.MailInABox.Client
{
    public interface ITokenContainer<TTokenBase> where TTokenBase : TokenBase
    {
        List<TTokenBase> Tokens { get; set; }
    }
    
    /// <summary>
    /// A container for a collection of tokens.
    /// </summary>
    /// <typeparam name="TTokenBase"></typeparam>
    public sealed class TokenContainer<TTokenBase> : ITokenContainer<TTokenBase> where TTokenBase : TokenBase
    {
        /// <summary>
        /// The collection of tokens
        /// </summary>
        public List<TTokenBase> Tokens { get; set; } = new List<TTokenBase>();

        /// <summary>
        /// Instantiates a TokenContainer
        /// </summary>
        public TokenContainer()
        {
        }

        /// <summary>
        /// Instantiates a TokenContainer
        /// </summary>
        /// <param name="tokens"></param>
        public TokenContainer(System.Collections.Generic.IEnumerable<TTokenBase> tokens)
        {
            Tokens = tokens.ToList();
        }

        public TTokenBase[] GetTokens()
        {
            return Tokens.ToArray();
        }
    }
}