/*
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * The version of the OpenAPI document: 0.51.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Bdaya.MailInABox.Api;
using Bdaya.MailInABox.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Bdaya.MailInABox.Test.Api
{
    /// <summary>
    ///  Class for testing SSLApi
    /// </summary>
    public sealed class SSLApiTests : ApiTestsBase
    {
        private readonly ISSLApi _instance;

        public SSLApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ISSLApi>();
        }

        /// <summary>
        /// Test GenerateSSLCSR
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GenerateSSLCSRAsyncTest()
        {
            string domain = default!;
            string countrycode = default!;
            var response = await _instance.GenerateSSLCSRAsync(domain, countrycode);
            var model = response.AsModel();
            Assert.IsType<string>(model);
        }

        /// <summary>
        /// Test GetSSLStatus
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetSSLStatusAsyncTest()
        {
            var response = await _instance.GetSSLStatusAsync();
            var model = response.AsModel();
            Assert.IsType<SSLStatusResponse>(model);
        }

        /// <summary>
        /// Test InstallSSLCertificate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task InstallSSLCertificateAsyncTest()
        {
            string domain = default!;
            string cert = default!;
            string chain = default!;
            var response = await _instance.InstallSSLCertificateAsync(domain, cert, chain);
            var model = response.AsModel();
            Assert.IsType<string>(model);
        }

        /// <summary>
        /// Test ProvisionSSLCertificates
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ProvisionSSLCertificatesAsyncTest()
        {
            var response = await _instance.ProvisionSSLCertificatesAsync();
            var model = response.AsModel();
            Assert.IsType<SSLCertificatesProvisionResponse>(model);
        }
    }
}
