// <auto-generated>
/*
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * The version of the OpenAPI document: 0.51.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = Bdaya.MailInABox.Client.ClientUtils;

namespace Bdaya.MailInABox.Model
{
    /// <summary>
    /// Response format (&#x60;application/json&#x60; or &#x60;text/html&#x60;).
    /// </summary>
    /// <value>Response format (&#x60;application/json&#x60; or &#x60;text/html&#x60;).</value>
    public enum MailUsersResponseFormat
    {
        /// <summary>
        /// Enum Text for value: text
        /// </summary>
        Text = 1,

        /// <summary>
        /// Enum Json for value: json
        /// </summary>
        Json = 2
    }

    /// <summary>
    /// Converts <see cref="MailUsersResponseFormat"/> to and from the JSON value
    /// </summary>
    public static class MailUsersResponseFormatValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="MailUsersResponseFormat"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MailUsersResponseFormat FromString(string value)
        {
            if (value.Equals("text"))
                return MailUsersResponseFormat.Text;

            if (value.Equals("json"))
                return MailUsersResponseFormat.Json;

            throw new NotImplementedException($"Could not convert value to type MailUsersResponseFormat: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="MailUsersResponseFormat"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MailUsersResponseFormat? FromStringOrDefault(string value)
        {
            if (value.Equals("text"))
                return MailUsersResponseFormat.Text;

            if (value.Equals("json"))
                return MailUsersResponseFormat.Json;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="MailUsersResponseFormat"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(MailUsersResponseFormat value)
        {
            if (value == MailUsersResponseFormat.Text)
                return "text";

            if (value == MailUsersResponseFormat.Json)
                return "json";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailUsersResponseFormat"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class MailUsersResponseFormatJsonConverter : JsonConverter<MailUsersResponseFormat>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override MailUsersResponseFormat Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            MailUsersResponseFormat? result = rawValue == null
                ? null
                : MailUsersResponseFormatValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the MailUsersResponseFormat to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailUsersResponseFormat"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, MailUsersResponseFormat mailUsersResponseFormat, JsonSerializerOptions options)
        {
            writer.WriteStringValue(mailUsersResponseFormat.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailUsersResponseFormat"/>
    /// </summary>
    public class MailUsersResponseFormatNullableJsonConverter : JsonConverter<MailUsersResponseFormat?>
    {
        /// <summary>
        /// Returns a MailUsersResponseFormat from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override MailUsersResponseFormat? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            MailUsersResponseFormat? result = rawValue == null
                ? null
                : MailUsersResponseFormatValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailUsersResponseFormat"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, MailUsersResponseFormat? mailUsersResponseFormat, JsonSerializerOptions options)
        {
            writer.WriteStringValue(mailUsersResponseFormat?.ToString() ?? "null");
        }
    }
}
