// <auto-generated>
/*
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * The version of the OpenAPI document: 0.51.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = Bdaya.MailInABox.Client.ClientUtils;

namespace Bdaya.MailInABox.Model
{
    /// <summary>
    /// Mail user details.
    /// </summary>
    public partial class MailUser : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailUser" /> class.
        /// </summary>
        /// <param name="email">Email format.</param>
        /// <param name="mailbox">mailbox</param>
        /// <param name="privileges">privileges</param>
        /// <param name="status">status</param>
        [JsonConstructor]
        public MailUser(string email, string mailbox, List<MailUserPrivilege> privileges, MailUserStatus status)
        {
            Email = email;
            Mailbox = mailbox;
            Privileges = privileges;
            Status = status;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public MailUserStatus Status { get; set; }

        /// <summary>
        /// Email format.
        /// </summary>
        /// <value>Email format.</value>
        /// <example>user@example.com</example>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Mailbox
        /// </summary>
        /// <example>/home/user-data/mail/mailboxes/example.com/user</example>
        [JsonPropertyName("mailbox")]
        public string Mailbox { get; set; }

        /// <summary>
        /// Gets or Sets Privileges
        /// </summary>
        [JsonPropertyName("privileges")]
        public List<MailUserPrivilege> Privileges { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailUser {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Mailbox: ").Append(Mailbox).Append("\n");
            sb.Append("  Privileges: ").Append(Privileges).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailUser" />
    /// </summary>
    public class MailUserJsonConverter : JsonConverter<MailUser>
    {
        /// <summary>
        /// Deserializes json to <see cref="MailUser" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailUser Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            string? email = default;
            string? mailbox = default;
            List<MailUserPrivilege>? privileges = default;
            MailUserStatus? status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email":
                            email = utf8JsonReader.GetString();
                            break;
                        case "mailbox":
                            mailbox = utf8JsonReader.GetString();
                            break;
                        case "privileges":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                privileges = JsonSerializer.Deserialize<List<MailUserPrivilege>>(ref utf8JsonReader, jsonSerializerOptions);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            status = statusRawValue == null
                                ? null
                                : MailUserStatusValueConverter.FromStringOrDefault(statusRawValue);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (email == null)
                throw new ArgumentNullException(nameof(email), "Property is required for class MailUser.");

            if (mailbox == null)
                throw new ArgumentNullException(nameof(mailbox), "Property is required for class MailUser.");

            if (privileges == null)
                throw new ArgumentNullException(nameof(privileges), "Property is required for class MailUser.");

            if (status == null)
                throw new ArgumentNullException(nameof(status), "Property is required for class MailUser.");

            return new MailUser(email, mailbox, privileges, status.Value);
        }

        /// <summary>
        /// Serializes a <see cref="MailUser" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailUser"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailUser mailUser, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, mailUser, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailUser" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailUser"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, MailUser mailUser, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("email", mailUser.Email);
            writer.WriteString("mailbox", mailUser.Mailbox);
            writer.WritePropertyName("privileges");
            JsonSerializer.Serialize(writer, mailUser.Privileges, jsonSerializerOptions);
            var statusRawValue = MailUserStatusValueConverter.ToJsonValue(mailUser.Status);

            if (statusRawValue != null)
                writer.WriteString("status", statusRawValue);
            else
                writer.WriteNull("status");
        }
    }
}
