// <auto-generated>
/*
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * The version of the OpenAPI document: 0.51.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = Bdaya.MailInABox.Client.ClientUtils;

namespace Bdaya.MailInABox.Model
{
    /// <summary>
    /// Mail alias details.
    /// </summary>
    public partial class MailAlias : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailAlias" /> class.
        /// </summary>
        /// <param name="address">Email format.</param>
        /// <param name="addressDisplay">Email format.</param>
        /// <param name="forwardsTo">forwardsTo</param>
        /// <param name="auto">auto</param>
        /// <param name="permittedSenders">permittedSenders</param>
        [JsonConstructor]
        public MailAlias(string address, string addressDisplay, List<string> forwardsTo, bool auto, List<string>? permittedSenders = default)
        {
            Address = address;
            AddressDisplay = addressDisplay;
            ForwardsTo = forwardsTo;
            Auto = auto;
            PermittedSenders = permittedSenders;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Email format.
        /// </summary>
        /// <value>Email format.</value>
        /// <example>user@example.com</example>
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Email format.
        /// </summary>
        /// <value>Email format.</value>
        /// <example>user@example.com</example>
        [JsonPropertyName("address_display")]
        public string AddressDisplay { get; set; }

        /// <summary>
        /// Gets or Sets ForwardsTo
        /// </summary>
        [JsonPropertyName("forwards_to")]
        public List<string> ForwardsTo { get; set; }

        /// <summary>
        /// Gets or Sets Auto
        /// </summary>
        /// <example>true</example>
        [JsonPropertyName("auto")]
        public bool Auto { get; set; }

        /// <summary>
        /// Gets or Sets PermittedSenders
        /// </summary>
        [JsonPropertyName("permitted_senders")]
        public List<string>? PermittedSenders { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailAlias {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  AddressDisplay: ").Append(AddressDisplay).Append("\n");
            sb.Append("  ForwardsTo: ").Append(ForwardsTo).Append("\n");
            sb.Append("  Auto: ").Append(Auto).Append("\n");
            sb.Append("  PermittedSenders: ").Append(PermittedSenders).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailAlias" />
    /// </summary>
    public class MailAliasJsonConverter : JsonConverter<MailAlias>
    {
        /// <summary>
        /// Deserializes json to <see cref="MailAlias" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailAlias Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            string? address = default;
            string? addressDisplay = default;
            List<string>? forwardsTo = default;
            bool? auto = default;
            List<string>? permittedSenders = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = utf8JsonReader.GetString();
                            break;
                        case "address_display":
                            addressDisplay = utf8JsonReader.GetString();
                            break;
                        case "forwards_to":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                forwardsTo = JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions);
                            break;
                        case "auto":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                auto = utf8JsonReader.GetBoolean();
                            break;
                        case "permitted_senders":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                permittedSenders = JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (address == null)
                throw new ArgumentNullException(nameof(address), "Property is required for class MailAlias.");

            if (addressDisplay == null)
                throw new ArgumentNullException(nameof(addressDisplay), "Property is required for class MailAlias.");

            if (forwardsTo == null)
                throw new ArgumentNullException(nameof(forwardsTo), "Property is required for class MailAlias.");
            
            if (auto == null)
                throw new ArgumentNullException(nameof(auto), "Property is required for class MailAlias.");

            return new MailAlias(address, addressDisplay, forwardsTo, auto.Value, permittedSenders);
        }

        /// <summary>
        /// Serializes a <see cref="MailAlias" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailAlias"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailAlias mailAlias, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, mailAlias, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailAlias" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailAlias"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, MailAlias mailAlias, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("address", mailAlias.Address);
            writer.WriteString("address_display", mailAlias.AddressDisplay);
            writer.WritePropertyName("forwards_to");
            JsonSerializer.Serialize(writer, mailAlias.ForwardsTo, jsonSerializerOptions);
            writer.WriteBoolean("auto", mailAlias.Auto);
            writer.WritePropertyName("permitted_senders");
            JsonSerializer.Serialize(writer, mailAlias.PermittedSenders, jsonSerializerOptions);
        }
    }
}
