// <auto-generated>
/*
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * The version of the OpenAPI document: 0.51.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = Bdaya.MailInABox.Client.ClientUtils;

namespace Bdaya.MailInABox.Model
{
    /// <summary>
    /// Me (user) authentication result.
    /// </summary>
    /// <value>Me (user) authentication result.</value>
    public enum MeAuthStatus
    {
        /// <summary>
        /// Enum Ok for value: ok
        /// </summary>
        Ok = 1,

        /// <summary>
        /// Enum Invalid for value: invalid
        /// </summary>
        Invalid = 2
    }

    /// <summary>
    /// Converts <see cref="MeAuthStatus"/> to and from the JSON value
    /// </summary>
    public static class MeAuthStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="MeAuthStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MeAuthStatus FromString(string value)
        {
            if (value.Equals("ok"))
                return MeAuthStatus.Ok;

            if (value.Equals("invalid"))
                return MeAuthStatus.Invalid;

            throw new NotImplementedException($"Could not convert value to type MeAuthStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="MeAuthStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MeAuthStatus? FromStringOrDefault(string value)
        {
            if (value.Equals("ok"))
                return MeAuthStatus.Ok;

            if (value.Equals("invalid"))
                return MeAuthStatus.Invalid;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="MeAuthStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(MeAuthStatus value)
        {
            if (value == MeAuthStatus.Ok)
                return "ok";

            if (value == MeAuthStatus.Invalid)
                return "invalid";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MeAuthStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class MeAuthStatusJsonConverter : JsonConverter<MeAuthStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override MeAuthStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            MeAuthStatus? result = rawValue == null
                ? null
                : MeAuthStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the MeAuthStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="meAuthStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, MeAuthStatus meAuthStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(meAuthStatus.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MeAuthStatus"/>
    /// </summary>
    public class MeAuthStatusNullableJsonConverter : JsonConverter<MeAuthStatus?>
    {
        /// <summary>
        /// Returns a MeAuthStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override MeAuthStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            MeAuthStatus? result = rawValue == null
                ? null
                : MeAuthStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="meAuthStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, MeAuthStatus? meAuthStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(meAuthStatus?.ToString() ?? "null");
        }
    }
}
