// <auto-generated>
/*
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * The version of the OpenAPI document: 0.51.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = Bdaya.MailInABox.Client.ClientUtils;

namespace Bdaya.MailInABox.Model
{
    /// <summary>
    /// Me (user) response.
    /// </summary>
    public partial class MeResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MeResponse" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="apiKey">apiKey</param>
        /// <param name="email">Email format.</param>
        /// <param name="privileges">privileges</param>
        /// <param name="reason">reason</param>
        [JsonConstructor]
        public MeResponse(MeAuthStatus status, string? apiKey = default, string? email = default, List<MailUserPrivilege>? privileges = default, string? reason = default)
        {
            Status = status;
            ApiKey = apiKey;
            Email = email;
            Privileges = privileges;
            Reason = reason;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public MeAuthStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets ApiKey
        /// </summary>
        /// <example>12345abcde</example>
        [JsonPropertyName("api_key")]
        public string? ApiKey { get; set; }

        /// <summary>
        /// Email format.
        /// </summary>
        /// <value>Email format.</value>
        /// <example>user@example.com</example>
        [JsonPropertyName("email")]
        public string? Email { get; set; }

        /// <summary>
        /// Gets or Sets Privileges
        /// </summary>
        [JsonPropertyName("privileges")]
        public List<MailUserPrivilege>? Privileges { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        /// <example>Incorrect username or password</example>
        [JsonPropertyName("reason")]
        public string? Reason { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MeResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ApiKey: ").Append(ApiKey).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Privileges: ").Append(Privileges).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MeResponse" />
    /// </summary>
    public class MeResponseJsonConverter : JsonConverter<MeResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="MeResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MeResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            MeAuthStatus? status = default;
            string? apiKey = default;
            string? email = default;
            List<MailUserPrivilege>? privileges = default;
            string? reason = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            status = statusRawValue == null
                                ? null
                                : MeAuthStatusValueConverter.FromStringOrDefault(statusRawValue);
                            break;
                        case "api_key":
                            apiKey = utf8JsonReader.GetString();
                            break;
                        case "email":
                            email = utf8JsonReader.GetString();
                            break;
                        case "privileges":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                privileges = JsonSerializer.Deserialize<List<MailUserPrivilege>>(ref utf8JsonReader, jsonSerializerOptions);
                            break;
                        case "reason":
                            reason = utf8JsonReader.GetString();
                            break;
                        default:
                            break;
                    }
                }
            }

            if (status == null)
                throw new ArgumentNullException(nameof(status), "Property is required for class MeResponse.");

            return new MeResponse(status.Value, apiKey, email, privileges, reason);
        }

        /// <summary>
        /// Serializes a <see cref="MeResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="meResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MeResponse meResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, meResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MeResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="meResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, MeResponse meResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            var statusRawValue = MeAuthStatusValueConverter.ToJsonValue(meResponse.Status);

            if (statusRawValue != null)
                writer.WriteString("status", statusRawValue);
            else
                writer.WriteNull("status");

            writer.WriteString("api_key", meResponse.ApiKey);
            writer.WriteString("email", meResponse.Email);
            writer.WritePropertyName("privileges");
            JsonSerializer.Serialize(writer, meResponse.Privileges, jsonSerializerOptions);
            writer.WriteString("reason", meResponse.Reason);
        }
    }
}
