// <auto-generated>
/*
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present. 
 *
 * The version of the OpenAPI document: 0.51.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = Bdaya.MailInABox.Client.ClientUtils;

namespace Bdaya.MailInABox.Model
{
    /// <summary>
    /// MfaStatusResponseNewMfa
    /// </summary>
    public partial class MfaStatusResponseNewMfa : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MfaStatusResponseNewMfa" /> class.
        /// </summary>
        /// <param name="qrCodeBase64">qrCodeBase64</param>
        /// <param name="secret">secret</param>
        /// <param name="type">type</param>
        [JsonConstructor]
        public MfaStatusResponseNewMfa(string qrCodeBase64, string secret, string type)
        {
            QrCodeBase64 = qrCodeBase64;
            Secret = secret;
            Type = type;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets QrCodeBase64
        /// </summary>
        [JsonPropertyName("qr_code_base64")]
        public string QrCodeBase64 { get; set; }

        /// <summary>
        /// Gets or Sets Secret
        /// </summary>
        [JsonPropertyName("secret")]
        public string Secret { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MfaStatusResponseNewMfa {\n");
            sb.Append("  QrCodeBase64: ").Append(QrCodeBase64).Append("\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MfaStatusResponseNewMfa" />
    /// </summary>
    public class MfaStatusResponseNewMfaJsonConverter : JsonConverter<MfaStatusResponseNewMfa>
    {
        /// <summary>
        /// Deserializes json to <see cref="MfaStatusResponseNewMfa" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MfaStatusResponseNewMfa Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            string? qrCodeBase64 = default;
            string? secret = default;
            string? type = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "qr_code_base64":
                            qrCodeBase64 = utf8JsonReader.GetString();
                            break;
                        case "secret":
                            secret = utf8JsonReader.GetString();
                            break;
                        case "type":
                            type = utf8JsonReader.GetString();
                            break;
                        default:
                            break;
                    }
                }
            }

            if (qrCodeBase64 == null)
                throw new ArgumentNullException(nameof(qrCodeBase64), "Property is required for class MfaStatusResponseNewMfa.");

            if (secret == null)
                throw new ArgumentNullException(nameof(secret), "Property is required for class MfaStatusResponseNewMfa.");

            if (type == null)
                throw new ArgumentNullException(nameof(type), "Property is required for class MfaStatusResponseNewMfa.");

            return new MfaStatusResponseNewMfa(qrCodeBase64, secret, type);
        }

        /// <summary>
        /// Serializes a <see cref="MfaStatusResponseNewMfa" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mfaStatusResponseNewMfa"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MfaStatusResponseNewMfa mfaStatusResponseNewMfa, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, mfaStatusResponseNewMfa, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MfaStatusResponseNewMfa" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mfaStatusResponseNewMfa"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, MfaStatusResponseNewMfa mfaStatusResponseNewMfa, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("qr_code_base64", mfaStatusResponseNewMfa.QrCodeBase64);
            writer.WriteString("secret", mfaStatusResponseNewMfa.Secret);
            writer.WriteString("type", mfaStatusResponseNewMfa.Type);
        }
    }
}
